# Generated by Django 4.0.3 on 2022-04-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(choices=[('t', 'Tall'), ('s', 'Short')], max_length=1)),
                ('colour', models.CharField(choices=[('d', 'Dark'), ('l', 'Light')], max_length=1)),
                ('filling', models.CharField(choices=[('f', 'Full'), ('e', 'Empty')], max_length=1)),
                ('shape', models.CharField(choices=[('r', 'Round'), ('s', 'Square')], max_length=1)),
            ],
            options={
                'unique_together': {('height', 'colour', 'filling', 'shape')},
            },
        ),
    ]
